#!/bin/bash

CSS="-html4.css.url:../jf_modify.css -html4.css.include:link -masterLocale:en -locale:en,ja"

target_dir=$1
base=$2

sxmlcnv  -p  ${base}.scm > ${base}.sdoc
/usr/local/bin/sdoc ${CSS} ${base}.sdoc
