#!/bin/bash

CSS="-html4.css.url:../sumibi.css -html4.encoding:UTF-8 -html4.css.include:link -masterLocale:ja -locale:en,ja"

base=$1
CSS_OP=""
if [[ "$2" != "" ]] ; then
    CSS_OP="-toc:true"
fi

gosh -I../../../lib /usr/local/bin/sxmlcnv  -p  ${base}.scm > ${base}.sdoc
/usr/local/bin/sdoc ${CSS} ${CSS_OP} ${base}.sdoc
